spring:
  datasource:
    url: jdbc:h2:mem:money_test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

redis:
  host: localhost
  port: 6379